var womanShoesDB = [
  { id: 1, title: "woman shoe", price: "45", imageUrl: "Images/woman1.png", qnt: 1 },
  { id: 2, title: "woman shoe", price: "35", imageUrl: "Images/woman2.png", qnt: 1 },
  { id: 3, title: "woman shoe", price: "30", imageUrl: "Images/woman3.png", qnt: 1 },
  { id: 4, title: "woman shoe", price: "50", imageUrl: "Images/woman4.png", qnt: 1 },
  { id: 5, title: "woman shoe", price: "25", imageUrl: "Images/woman5.png", qnt: 1 },
  { id: 6, title: "woman shoe", price: "40", imageUrl: "Images/woman6.png", qnt: 1 },
  { id: 7, title: "woman shoe", price: "30", imageUrl: "Images/woman7.png", qnt: 1 },
  { id: 8, title: "woman shoe", price: "45", imageUrl: "Images/woman8.png", qnt: 1 },
  { id: 9, title: "woman shoe", price: "35", imageUrl: "Images/woman9.png", qnt: 1 },
  { id: 10, title: "woman shoe", price: "60", imageUrl: "Images/woman10.png", qnt: 1 },
  { id: 11, title: "woman shoe", price: "40", imageUrl: "Images/woman11.png", qnt: 1 },
  { id: 12, title: "woman shoe", price: "25", imageUrl: "Images/woman12.png", qnt: 1 },
]

var menShoesDB = [
  { id: 13, title: "man shoe", price: "20", imageUrl: "Images/man1.png", qnt: 1 },
  { id: 14, title: "man shoe", price: "25", imageUrl: "Images/man2.png", qnt: 1 },
  { id: 15, title: "man shoe", price: "45", imageUrl: "Images/man3.png", qnt: 1 },
  { id: 16, title: "man shoe", price: "50", imageUrl: "Images/man4.png", qnt: 1 },
  { id: 17, title: "man shoe", price: "25", imageUrl: "Images/man5.png", qnt: 1 },
  { id: 18, title: "man shoe", price: "40", imageUrl: "Images/man6.png", qnt: 1 },
  { id: 19, title: "man shoe", price: "35", imageUrl: "Images/man7.png", qnt: 1 },
  { id: 20, title: "man shoe", price: "40", imageUrl: "Images/man8.png", qnt: 1 },
  { id: 21, title: "man shoe", price: "25", imageUrl: "Images/man9.png", qnt: 1 },
  { id: 22, title: "man shoe", price: "18", imageUrl: "Images/man10.png", qnt: 1 },
  { id: 23, title: "man shoe", price: "30", imageUrl: "Images/man11.png", qnt: 1 },
  { id: 24, title: "man shoe", price: "65", imageUrl: "Images/man12.png", qnt: 1 },
  { id: 25, title: "man shoe", price: "20", imageUrl: "Images/man13.png", qnt: 1 },
  { id: 26, title: "man shoe", price: "25", imageUrl: "Images/man14.png", qnt: 1 },
  { id: 27, title: "man shoe", price: "45", imageUrl: "Images/man15.png", qnt: 1 },
  { id: 28, title: "man shoe", price: "50", imageUrl: "Images/man16.png", qnt: 1 },
  { id: 29, title: "man shoe", price: "25", imageUrl: "Images/man17.png", qnt: 1 },
  { id: 30, title: "man shoe", price: "40", imageUrl: "Images/man18.png", qnt: 1 },
  { id: 31, title: "man shoe", price: "35", imageUrl: "Images/man19.png", qnt: 1 },
  { id: 32, title: "man shoe", price: "40", imageUrl: "Images/man20.png", qnt: 1 },
]

var sportShoesDB = [
  { id: 33, title: "sport shoe", price: "30", imageUrl: "Images/sport1.png", qnt: 1 },
  { id: 34, title: "sport shoe", price: "45", imageUrl: "Images/sport2.png", qnt: 1 },
  { id: 35, title: "sport shoe", price: "45", imageUrl: "Images/sport3.png", qnt: 1 },
  { id: 36, title: "sport shoe", price: "50", imageUrl: "Images/sport4.png", qnt: 1 },
  { id: 37, title: "sport shoe", price: "35", imageUrl: "Images/sport5.png", qnt: 1 },
  { id: 38, title: "sport shoe", price: "40", imageUrl: "Images/sport6.png", qnt: 1 },
  { id: 39, title: "sport shoe", price: "55", imageUrl: "Images/sport7.png", qnt: 1 },
  { id: 40, title: "sport shoe", price: "40", imageUrl: "Images/sport8.png", qnt: 1 },
  { id: 41, title: "sport shoe", price: "75", imageUrl: "Images/sport9.png", qnt: 1 },
  { id: 42, title: "sport shoe", price: "60", imageUrl: "Images/sport10.png", qnt: 1 },
  { id: 43, title: "sport shoe", price: "30", imageUrl: "Images/sport11.png", qnt: 1 },
  { id: 44, title: "sport shoe", price: "65", imageUrl: "Images/sport12.png", qnt: 1 },
  { id: 45, title: "sport shoe", price: "40", imageUrl: "Images/sport13.png", qnt: 1 },
  { id: 46, title: "sport shoe", price: "55", imageUrl: "Images/sport14.png", qnt: 1 },
  { id: 47, title: "sport shoe", price: "45", imageUrl: "Images/sport15.png", qnt: 1 },
  { id: 48, title: "sport shoe", price: "35", imageUrl: "Images/sport16.png", qnt: 1 }
]